package UserInterface;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class roomconfig extends javax.swing.JFrame {

    private Connection con=null;
    private ResultSet rs;
    private Statement stmnt;
    String userProfileID;
    /**
     * Creates new form roomconfig
     */
    public roomconfig() {
        initComponents();
         con=dbConnection.con();
    }
    public roomconfig(String userID)
    {
        userProfileID=userID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblEditpro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCreateroom = new javax.swing.JLabel();
        lblRoomid1 = new javax.swing.JLabel();
        lblDesp = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        spiSize = new javax.swing.JSpinner();
        btnUpdate = new javax.swing.JButton();
        cbRoom = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesp = new javax.swing.JTextArea();
        menubar = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuitemUprofile = new javax.swing.JMenuItem();
        menuitemViewUser = new javax.swing.JMenuItem();
        menuRoom = new javax.swing.JMenu();
        menuitemCrRoom = new javax.swing.JMenuItem();
        menuitemConfig = new javax.swing.JMenuItem();
        menuitemHistory = new javax.swing.JMenuItem();
        menuitemExit = new javax.swing.JMenuItem();

        jPanel2.setBackground(java.awt.SystemColor.control);

        lblEditpro.setBackground(java.awt.SystemColor.control);
        lblEditpro.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblEditpro.setText("Edit Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblEditpro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditpro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secure Net Messenger");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.text);

        jPanel3.setBackground(java.awt.SystemColor.control);

        lblCreateroom.setBackground(java.awt.SystemColor.control);
        lblCreateroom.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCreateroom.setText("Configure Chat Room");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCreateroom, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblRoomid1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblDesp.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDesp.setText("Description");

        lblSize.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblSize.setText("Size");

        spiSize.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));

        btnUpdate.setBackground(new java.awt.Color(153, 0, 0));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnUpdate.setForeground(java.awt.SystemColor.text);
        btnUpdate.setText("Update");
        btnUpdate.setName("btnLogin"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cbRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomActionPerformed(evt);
            }
        });
        cbRoom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbRoomPropertyChange(evt);
            }
        });

        txtDesp.setColumns(20);
        txtDesp.setLineWrap(true);
        txtDesp.setRows(5);
        jScrollPane1.setViewportView(txtDesp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblRoomid1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSize)
                            .addComponent(lblDesp)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbRoom, javax.swing.GroupLayout.Alignment.LEADING, 0, 97, Short.MAX_VALUE)
                                .addComponent(spiSize, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 179, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spiSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblRoomid1)
                .addGap(15, 15, 15))
        );

        menuUser.setText("User Tool");

        menuitemUprofile.setText("user profile");
        menuitemUprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemUprofileActionPerformed(evt);
            }
        });
        menuUser.add(menuitemUprofile);

        menuitemViewUser.setText("view user");
        menuUser.add(menuitemViewUser);

        menubar.add(menuUser);

        menuRoom.setText("Room Control");

        menuitemCrRoom.setText("create room");
        menuitemCrRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemCrRoomActionPerformed(evt);
            }
        });
        menuRoom.add(menuitemCrRoom);

        menuitemConfig.setText("configure room");
        menuRoom.add(menuitemConfig);

        menuitemHistory.setText("room history");
        menuRoom.add(menuitemHistory);

        menuitemExit.setText("exit");
        menuRoom.add(menuitemExit);

        menubar.add(menuRoom);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowActivated

    private void menuitemUprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemUprofileActionPerformed
        // TODO add your handling code here:
        new userprofile().setVisible(true);
    }//GEN-LAST:event_menuitemUprofileActionPerformed

    private void menuitemCrRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemCrRoomActionPerformed
        // TODO add your handling code here:
        new createroom().setVisible(true);
    }//GEN-LAST:event_menuitemCrRoomActionPerformed

    private void cbRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomActionPerformed
        // TODO add your handling code here:
        String selectedRoom=(String) cbRoom.getSelectedItem();
        String qrySel="select room_size,room_desc from chat_room where room_name='"+selectedRoom+"';";
        try {
            Statement stmnt=con.createStatement();
            rs=stmnt.executeQuery(qrySel);
            rs.next();
            spiSize.setValue(rs.getInt("room_size"));
            txtDesp.setText(rs.getString("room_desc"));
        } catch (SQLException ex) {
            Logger.getLogger(roomconfig.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cbRoomActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String selectedRoom=(String) cbRoom.getSelectedItem();
        int room_size=(int) spiSize.getValue();
        String room_desc=txtDesp.getText();
        String qryUpt="update chat_room set room_size="+room_size+",room_desc='"+room_desc+"' where room_name='"+selectedRoom+"';";
        try {
            Statement stmnt=con.createStatement();
            int result=stmnt.executeUpdate(qryUpt);
            if(result!=0)
            {
                JOptionPane.showMessageDialog(null,"chat room updated");
            }
        } catch (SQLException ex) {
            Logger.getLogger(roomconfig.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String qrySel="select * from chat_room where room_link='"+chatwindow.link+"';";
        
        try {
            stmnt=con.createStatement();
            rs=stmnt.executeQuery(qrySel);
            while(rs.next())
            {
                cbRoom.addItem(rs.getString("room_name"));
            }
           /* int room_size=rs.getInt("room_size");
                String room_desc=rs.getString("room_desc");
                spiSize.setValue(room_size);
                txtDesp.setText(room_desc);*/
        } catch (SQLException ex) {
            Logger.getLogger(roomconfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void cbRoomPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbRoomPropertyChange
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_cbRoomPropertyChange

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roomconfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roomconfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roomconfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roomconfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomconfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbRoom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateroom;
    private javax.swing.JLabel lblDesp;
    private javax.swing.JLabel lblEditpro;
    private javax.swing.JLabel lblRoomid1;
    private javax.swing.JLabel lblSize;
    private javax.swing.JMenu menuRoom;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitemConfig;
    private javax.swing.JMenuItem menuitemCrRoom;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemHistory;
    private javax.swing.JMenuItem menuitemUprofile;
    private javax.swing.JMenuItem menuitemViewUser;
    private javax.swing.JSpinner spiSize;
    private javax.swing.JTextArea txtDesp;
    // End of variables declaration//GEN-END:variables
}
