package UserInterface;




import com.mysql.cj.jdbc.Blob;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class userprofile extends javax.swing.JFrame {
    private String CountryName=null;
    public static String userProfileID;
    private Connection con=null;
    private String qryUpt1,qryUpt2;
    private ResultSet rs ;
    private int rowCount;
    public String firstname,lastname,email,gender="",myself;
    private String qryIn;
    private Date SelectedDate,DBDate;
    private ImageIcon DBImage;
    private int con_code;
    String country;
    /**
     * Creates new form userprofile
     */
    public userprofile() {
        initComponents();
    }
    public userprofile(String userProfileID1)
    {
        userProfileID=userProfileID1;
    }
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btgrpGender = new javax.swing.ButtonGroup();
        pnlBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblEditpro = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblUid = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        dtpickerDOB = new com.toedter.calendar.JDateChooser();
        lblMyself = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaMyself = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbOther = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        txtUid = new javax.swing.JTextField();
        lblcountry = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<>();
        menubar = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuitemUprofile = new javax.swing.JMenuItem();
        menuRoom = new javax.swing.JMenu();
        menuitemCrRoom = new javax.swing.JMenuItem();

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEmail.setName("txtUname"); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setText("E-mail");
        lblEmail.setName("lblUsername"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secure Net Messenger");
        setBackground(java.awt.SystemColor.text);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBody.setBackground(java.awt.SystemColor.text);

        jPanel1.setBackground(java.awt.SystemColor.control);

        lblEditpro.setBackground(java.awt.SystemColor.control);
        lblEditpro.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblEditpro.setText("Edit Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblEditpro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditpro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField1.setBackground(new java.awt.Color(0, 204, 0));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        lblUid.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblUid.setText("User_ID");
        lblUid.setName("lblUser_ID"); // NOI18N

        txtLname.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLname.setName("txtUname"); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        lblFname.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblFname.setText("Firstname");
        lblFname.setToolTipText("");
        lblFname.setName("lblUsername"); // NOI18N

        txtFname.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtFname.setName("txtUname"); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        lblLname.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblLname.setText("Lastname");
        lblLname.setName("lblUsername"); // NOI18N

        txtEmail1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEmail1.setName("txtUname"); // NOI18N
        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });

        lblEmail1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblEmail1.setText("E-mail");
        lblEmail1.setName("lblUsername"); // NOI18N

        lblDOB.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDOB.setText("Date of birth");
        lblDOB.setName("lblUsername"); // NOI18N

        dtpickerDOB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtpickerDOBPropertyChange(evt);
            }
        });

        lblMyself.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblMyself.setText("Myself");
        lblMyself.setName("lblUsername"); // NOI18N

        txtareaMyself.setColumns(20);
        txtareaMyself.setLineWrap(true);
        txtareaMyself.setRows(5);
        jScrollPane1.setViewportView(txtareaMyself);

        btnUpdate.setBackground(new java.awt.Color(204, 0, 0));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnUpdate.setForeground(java.awt.SystemColor.text);
        btnUpdate.setText("Update");
        btnUpdate.setName("btnLogin"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblGender.setText("Gender");
        lblGender.setName("lblUsername"); // NOI18N

        btgrpGender.add(rbMale);
        rbMale.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rbMale.setText("Male");

        btgrpGender.add(rbOther);
        rbOther.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rbOther.setText("Other");

        btgrpGender.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rbFemale.setText("Female");

        txtUid.setEditable(false);
        txtUid.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtUid.setName("txtUname"); // NOI18N
        txtUid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUidActionPerformed(evt);
            }
        });

        lblcountry.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblcountry.setText("Select country");
        lblcountry.setName("lblUsername"); // NOI18N

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "Nepal", "New Zealand", "Pakistan", "South Africa", "Sri Lanka", "Switzerland", "UK", "USA", "Japan", "China", "Australia", "others" }));
        cbCountry.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbCountryPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOther)
                            .addComponent(rbFemale)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblUid)
                                .addComponent(lblLname)
                                .addComponent(txtLname)
                                .addComponent(lblFname)
                                .addComponent(txtFname)
                                .addComponent(lblGender)
                                .addComponent(rbMale)
                                .addComponent(txtUid, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMyself)
                            .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEmail1)
                                .addComponent(txtEmail1)
                                .addComponent(lblDOB)
                                .addComponent(dtpickerDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblcountry)
                                .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail1)
                            .addComponent(lblUid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname)
                            .addComponent(lblDOB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dtpickerDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname)
                            .addComponent(lblcountry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblMyself)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addGap(4, 4, 4)
                                .addComponent(rbMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOther)))
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuUser.setText("User Tool");

        menuitemUprofile.setText("user profile");
        menuitemUprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemUprofileActionPerformed(evt);
            }
        });
        menuUser.add(menuitemUprofile);

        menubar.add(menuUser);

        menuRoom.setText("Room Control");

        menuitemCrRoom.setText("create room");
        menuitemCrRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemCrRoomActionPerformed(evt);
            }
        });
        menuRoom.add(menuitemCrRoom);

        menubar.add(menuRoom);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String firstnameL,lastnameL,emailL,genderL = null,myselfL;
      
        
           try
      {
          con=dbConnection.con();
          firstnameL=txtFname.getText();
          lastnameL=txtLname.getText();
          emailL=txtEmail.getText();
          
          
          java.sql.Date sqlDate = new java.sql.Date(SelectedDate.getTime());
         
    
          if(rbMale.isSelected())
          {
              genderL="Male";
          }
          else if(rbFemale.isSelected())
          {
              genderL="Female";
          }
          else if(rbOther.isSelected())
          {
              genderL="Other";
          }
          else{}
          myselfL=txtareaMyself.getText();
          
          qryUpt1="update user_profile set firstname='"+firstnameL+"',lastname='"+lastnameL+"',email='"+email+"',dob='"+sqlDate+"',myself='"+myselfL+"',gender='"+genderL+"' where user_id='"+userProfileID+"';";
          qryUpt2="update country_details set country_name='"+country+"',country_code="+con_code+";";
          Statement stmnt=con.createStatement();
                    int result1=stmnt.executeUpdate(qryUpt1);
                    int result2=stmnt.executeUpdate(qryUpt2);
                    if(result1 != 0 && result2!=0)
                    {
                        JOptionPane.showMessageDialog(null, "Profile is updated");
                        dispose();
                    }
                    else
                    {
                         JOptionPane.showMessageDialog(null, "Error:try again");
                    }
          
      }
      catch(HeadlessException | SQLException e)
      {
             JOptionPane.showMessageDialog(null,e);
      } 
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtUidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUidActionPerformed

    private void menuitemUprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemUprofileActionPerformed
        // TODO add your handling code here:
        dispose();
        new userprofile().setVisible(true);
    }//GEN-LAST:event_menuitemUprofileActionPerformed

    private void menuitemCrRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemCrRoomActionPerformed
        // TODO add your handling code here:
        new createroom().setVisible(true);
    }//GEN-LAST:event_menuitemCrRoomActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
        //userProfileID=log.getUserProfileID();
       // JOptionPane.showMessageDialog(null,userProfileID);
        try
      {
          con=dbConnection.con();
          
          String qrySel="select * from user_profile where user_id='"+userProfileID+"';";
          Statement stmnt=con.createStatement();
          rs = stmnt.executeQuery(qrySel);
          rs.next();
          firstname=rs.getString("firstname");
          lastname=rs.getString("lastname");
          email=rs.getString("email");
          gender=rs.getString("gender");
          myself=rs.getString("myself"); 
          DBDate=rs.getDate("dob");
          qrySel="select * from country_details where user_id='"+userProfileID+"';";
          stmnt=con.createStatement();
          rs = stmnt.executeQuery(qrySel);
          rs.next();
          CountryName=rs.getString("country_name");
                      
             
          
      }
      catch(Exception e)
      {
             JOptionPane.showMessageDialog(null,e);
      }
        txtUid.setText(userProfileID);
        txtFname.setText(firstname);
        txtLname.setText(lastname);
        txtEmail1.setText(email);
        txtareaMyself.setText(myself);
        dtpickerDOB.setDate(DBDate);
        cbCountry.setSelectedItem(CountryName);
        if(gender!=null)
        {
        if(gender.equalsIgnoreCase("Male"))
        {
            rbMale.setSelected(true);
        }
        else if(gender.equalsIgnoreCase("Female"))
        {
            rbFemale.setSelected(true);
        }
        else if(gender.equalsIgnoreCase("Other"))
        {
            rbOther.setSelected(true);
        }
        
        }
        else{}
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void dtpickerDOBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtpickerDOBPropertyChange
        // TODO add your handling code here:
        SelectedDate=dtpickerDOB.getDate();
        
               
    }//GEN-LAST:event_dtpickerDOBPropertyChange

    private void cbCountryPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbCountryPropertyChange
        // TODO add your handling code here:

        country=(String) cbCountry.getSelectedItem();
        switch(country)
        {
            case "India":
                con_code=356;
                break;
            case "Nepal":
                con_code=524;
                break;
            case "New Zealand":
                con_code=554;
                break;
            case "Pakistan":
                con_code=586;
                break;
            case "South Africa":
                con_code=710;
                break;
            case "Sri Lanka":
                con_code=144;
                break;
            case "Switzerland":
                con_code=756;
                break;
            case "UK":
                con_code=824;
                break;
            case "USA":
                con_code=840;
                break;
            case "Japan":
                con_code=392;
                break;
            case "China":
                con_code=156;
                break;
            case "Australia":
                con_code=036;
                break;
            case "Others":
                con_code=0;
                break;
               
            
        }
    }//GEN-LAST:event_cbCountryPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrpGender;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCountry;
    private com.toedter.calendar.JDateChooser dtpickerDOB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEditpro;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblMyself;
    private javax.swing.JLabel lblUid;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JMenu menuRoom;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitemCrRoom;
    private javax.swing.JMenuItem menuitemUprofile;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbOther;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtUid;
    private javax.swing.JTextArea txtareaMyself;
    // End of variables declaration//GEN-END:variables
}
