package UserInterface;



import java.sql.*;
import java.awt.Color;
import java.io.IOException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import static java.time.LocalDateTime.now;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 
 * @author DELL
 */
public class welcome extends javax.swing.JFrame {
    public String userProfileID;
    private Connection con=null;
    private String qryIn;
    private Statement stmnt;
    private String roomlink;
    private ResultSet rs;
    private String roomID;
    int size,current_member,flag=0;
    String type="member";
    
    
    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    public welcome(String UID)
    {
        userProfileID=UID;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCreateroom = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuitemUprofile = new javax.swing.JMenuItem();
        menuRoom = new javax.swing.JMenu();
        menuitemCrRoom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secure Net Messenger");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.text);
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(51, 0, 51));
        lblWelcome.setText("<html>\n<body>\n&emsp;&emsp;&nbsp;&nbsp;Welcome<br>\n&emsp;&emsp;&emsp;&emsp;To <br>\nSecure Net Messenger\n</body>\n</html>");

        jPanel3.setBackground(java.awt.SystemColor.control);

        lblCreateroom.setBackground(java.awt.SystemColor.control);
        lblCreateroom.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCreateroom.setText("Search Chatroom");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblCreateroom, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateroom, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        btnJoin.setBackground(new java.awt.Color(204, 0, 0));
        btnJoin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnJoin.setForeground(java.awt.SystemColor.text);
        btnJoin.setText("Join");
        btnJoin.setEnabled(false);
        btnJoin.setName("btnLogin"); // NOI18N
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        lblTime.setForeground(new java.awt.Color(255, 102, 0));
        lblTime.setText("time");

        txtLink.setForeground(new java.awt.Color(102, 102, 102));
        txtLink.setText("Paste chatroom joining link here");
        txtLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLinkMouseExited(evt);
            }
        });
        txtLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkActionPerformed(evt);
            }
        });
        txtLink.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtLinkPropertyChange(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(0, 204, 0));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        btnCheck.setBackground(new java.awt.Color(204, 0, 0));
        btnCheck.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCheck.setForeground(java.awt.SystemColor.text);
        btnCheck.setText("Verify Size");
        btnCheck.setName("btnLogin"); // NOI18N
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime))
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        menuUser.setText("User Tool");

        menuitemUprofile.setText("user profile");
        menuitemUprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemUprofileActionPerformed(evt);
            }
        });
        menuUser.add(menuitemUprofile);

        menubar.add(menuUser);

        menuRoom.setText("Room Control");

        menuitemCrRoom.setText("create room");
        menuitemCrRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemCrRoomActionPerformed(evt);
            }
        });
        menuRoom.add(menuitemCrRoom);

        menubar.add(menuRoom);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // TODO add your handling code here:
        
       
        String username=JOptionPane.showInputDialog("Enter your name for chatting : ");
        try
        { 
            userProfileID=loginform.uid;
            current_member+=1;
            con=dbConnection.con();
            String qryIn="insert into room_member_details values('"+roomID+"','"+userProfileID+"','"+type+"',"+flag+");";
            String qryUpt="update chat_room set current_member="+current_member+" where room_link='"+roomlink+"';";
            stmnt=con.createStatement();
            int result1=stmnt.executeUpdate(qryUpt);
            int result2=stmnt.executeUpdate(qryIn);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         Thread clientThread = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            chatwindow.makeClient(username);
                        } catch (Exception ex) {
                            Logger.getLogger(createroom.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                clientThread.start();
                dispose();
        new chatwindow(txtLink.getText()).setVisible(true);

       

    }//GEN-LAST:event_btnJoinActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Format dtf=new SimpleDateFormat("EEEE,MMM dd,yyyy");
        String str=dtf.format(new Date());
        lblTime.setText(str);
        btnJoin.setFocusable(true);
        btnJoin.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void txtLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLinkMouseEntered
        // TODO add your handling code here:
        txtLink.setText("");
        txtLink.setForeground(Color.blue);
    }//GEN-LAST:event_txtLinkMouseEntered

    private void txtLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLinkMouseExited
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtLinkMouseExited

    private void menuitemUprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemUprofileActionPerformed
        // TODO add your handling code here:
        new userprofile().setVisible(true);
    }//GEN-LAST:event_menuitemUprofileActionPerformed

    private void menuitemCrRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemCrRoomActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new createroom().setVisible(true);
    }//GEN-LAST:event_menuitemCrRoomActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      //  loginform log=new loginform();
       // userProfileID=log.getUserProfileID();
       
    }//GEN-LAST:event_formWindowOpened

    private void txtLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkActionPerformed

    private void txtLinkPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtLinkPropertyChange
//        // TODO add your handling code here:
//        //String qrySelSize="select room_size from chat_room where room_id='"+roomID+"'";
//        roomlink=txtLink.getText();
//        try
//        {
//            con=dbConnection.con();
//            String qrySel="Select room_id from chat_room where room_link='"+roomlink+"';";
//            stmnt=con.createStatement();
//            rs=stmnt.executeQuery(qrySel);
//            rs.next();
//            roomID=rs.getString("room_id");            
//            
//            
//        }
//        catch(Exception e)
//        {
//        }
//           
        
    }//GEN-LAST:event_txtLinkPropertyChange

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        roomlink=txtLink.getText();
        
       
             String qrySel="select room_size,current_member,room_id from chat_room where room_link='"+roomlink+"';";
             try
             {
             con=dbConnection.con();
             stmnt=con.createStatement();
             rs=stmnt.executeQuery(qrySel);
             rs.next();
             size=rs.getInt("room_size");
             current_member=rs.getInt("current_member");
             roomID=rs.getString("room_id");
               if(current_member<size)
                 {
                     btnJoin.setEnabled(true);
                 }
               else
                 {
                      JOptionPane.showMessageDialog(null,"chat room is packed");
                 }
             }
             catch(Exception e)
             {
             
             }
              
            
            
        
        
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnJoin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCreateroom;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenu menuRoom;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitemCrRoom;
    private javax.swing.JMenuItem menuitemUprofile;
    private javax.swing.JTextField txtLink;
    // End of variables declaration//GEN-END:variables
}
